image: node:12.20.0

pipelines:
  branches:
    master:
    - step:
        name: Build and Test
        caches:
          - node
        script: 
          - yarn
          - CI= yarn build
        artifacts:
          - build/**
    - step:
        name: Deploy
        script:
          - scp -r ./build/* ubuntu@18.141.119.178:~/app/petrapos-toplevel

      
